"""
REST API for the fine-tuned NER model.

Wraps ./ner_model_final in a FastAPI app with a single /predict endpoint
that takes raw text and returns detected entities.

Install:
    pip install fastapi uvicorn transformers torch

Run locally:
    uvicorn api:app --host 0.0.0.0 --port 8000

Then test with:
    curl -X POST "http://localhost:8000/predict" \
         -H "Content-Type: application/json" \
         -d '{"text": "Buhari visited Lagos yesterday"}'

Interactive docs (auto-generated by FastAPI) are at:
    http://localhost:8000/docs
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from transformers import pipeline
from typing import List

MODEL_PATH = "./ner_model_final"  # update if your model lives elsewhere

app = FastAPI(
    title="Nigerian Text NER API",
    description="Named entity recognition for noisy Nigerian X (Twitter) text",
    version="1.0.0",
)

# Loaded once at startup, reused across requests -- loading per-request would
# be extremely slow since it reloads model weights from disk every time.
ner_pipeline = None


@app.on_event("startup")
def load_model():
    global ner_pipeline
    print(f"Loading model from {MODEL_PATH} ...")
    ner_pipeline = pipeline(
        "token-classification",
        model=MODEL_PATH,
        tokenizer=MODEL_PATH,
        aggregation_strategy="simple",  # merges subword pieces into whole entities
    )
    print("Model loaded, API ready.")


class PredictRequest(BaseModel):
    text: str


class Entity(BaseModel):
    entity_group: str
    word: str
    score: float
    start: int
    end: int


class PredictResponse(BaseModel):
    text: str
    entities: List[Entity]


@app.get("/")
def health_check():
    return {"status": "ok", "model_loaded": ner_pipeline is not None}


@app.post("/predict", response_model=PredictResponse)
def predict(request: PredictRequest):
    if not request.text or not request.text.strip():
        raise HTTPException(status_code=400, detail="text field cannot be empty")

    if ner_pipeline is None:
        raise HTTPException(status_code=503, detail="Model is still loading, try again shortly")

    raw_results = ner_pipeline(request.text)

    entities = [
        Entity(
            entity_group=r["entity_group"],
            word=r["word"],
            score=float(r["score"]),  # numpy float32 -> plain float for JSON
            start=int(r["start"]),
            end=int(r["end"]),
        )
        for r in raw_results
    ]

    return PredictResponse(text=request.text, entities=entities)
