"""
REST API for the fine-tuned NER model.

Wraps ./ner_model_quantized (the quantized version) in a FastAPI app with a
single /predict endpoint that takes raw text and returns detected entities.

Run quantize_model.py first to produce ner_model_quantized from your
trained ner_model_final -- this is what makes the model fit in Render's
free-tier 512MB memory limit.

--- Failure-mode fixes applied in this version ---
1. (Fragmentation / truncation) After the model runs, gazetteer.find_spans_in_text()
   independently re-scans the ORIGINAL raw text for known entity strings and
   reconciles/merges/injects them against the model's raw predictions. This
   fixes cases like "Dangote Group" -> "gote Group" (truncation) and
   "Burna Boy" -> "Bur" + "na Boy" (fragmentation), since the gazetteer's
   authoritative strings are matched directly against clean input text,
   unaffected by how the model's subword tokenizer split things up.
2. (Fragmentation on names not in any gazetteer) aggregation_strategy switched
   from "simple" to "max", which is less prone to breaking one entity into
   multiple pieces when per-subword prediction confidence is inconsistent.
3. (Elision mismatch) Nigerian-language contractions like Igbo "n'Enugu" are
   lightly normalized (a space inserted after the apostrophe) before
   tokenization, so the tokenizer doesn't fuse the contraction and the
   following proper noun into one broken token.

Install:
    pip install fastapi uvicorn transformers torch

Run locally:
    uvicorn api:app --host 0.0.0.0 --port 8000

Then test with:
    curl -X POST "http://localhost:8000/predict" \
         -H "Content-Type: application/json" \
         -d '{"text": "Buhari visited Lagos yesterday"}'

Interactive docs (auto-generated by FastAPI) are at:
    http://localhost:8000/docs
"""

import re
import torch
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from transformers import pipeline, AutoModelForTokenClassification, AutoTokenizer, AutoConfig
from typing import List, Optional
from gazetteer_lookup import Gazetteer

# Point this at the QUANTIZED model folder produced by quantize_model.py,
# not the original ner_model_final -- the quantized version is what actually
# fits Render's free-tier memory limit.
MODEL_PATH = "./ner_model_quantized"

app = FastAPI(
    title="Nigerian Text NER API",
    description="Named entity recognition for noisy Nigerian X (Twitter) text",
    version="1.1.0",
)

# Loaded once at startup, reused across requests -- loading per-request would
# be extremely slow since it reloads model weights from disk every time.
ner_pipeline = None

# Gazetteer for fine-grained typing AND full-text span correction (see
# gazetteer_lookup.py's docstring for what changed and why).
gazetteer = Gazetteer("./gazetteers")

# Fix for Failure Mode 4 (orthographic elision mismatch): a single letter
# followed directly by an apostrophe then another letter with no space --
# e.g. Igbo "n'Enugu" -- gets a space inserted after the apostrophe, so the
# tokenizer doesn't fuse the contraction onto the following proper noun.
ELISION_PATTERN = re.compile(r"\b([A-Za-z])'(?=[A-Za-z])")


def normalize_elisions(text):
    return ELISION_PATTERN.sub(r"\1' ", text)


@app.on_event("startup")
def load_model():
    global ner_pipeline
    print(f"Loading quantized model from {MODEL_PATH} ...")

    # Quantized models can't be loaded with from_pretrained() directly, since
    # their state dict has a different internal structure (packed int8
    # params) than a normal float32 model. Instead: rebuild the same
    # architecture from config only, apply the same quantization, then load
    # the saved weights into that matching structure -- mirroring exactly
    # what quantize_model.py did when it created this folder.
    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
    config = AutoConfig.from_pretrained(MODEL_PATH)
    base_model = AutoModelForTokenClassification.from_config(config)
    quantized_model = torch.quantization.quantize_dynamic(
        base_model, {torch.nn.Linear}, dtype=torch.qint8
    )
    state_dict = torch.load(f"{MODEL_PATH}/pytorch_model.bin", map_location="cpu")
    quantized_model.load_state_dict(state_dict)
    quantized_model.eval()

    ner_pipeline = pipeline(
        "token-classification",
        model=quantized_model,
        tokenizer=tokenizer,
        # "max" (not "simple") is less prone to breaking one true entity
        # into multiple fragments when per-subword confidence is inconsistent
        # -- see Failure Mode 3 in testing (e.g. "Wizkid" -> "W" + "izkid").
        aggregation_strategy="max",
    )
    print("Model loaded, API ready.")


class PredictRequest(BaseModel):
    text: str


class Entity(BaseModel):
    entity_group: str
    word: str
    score: float
    start: int
    end: int
    subcategory: Optional[str] = None
    # True when this entity's span was corrected, merged from fragments, or
    # newly added by the gazetteer text-scan rather than coming directly
    # and unmodified from the model's own prediction.
    gazetteer_corrected: bool = False


class PredictResponse(BaseModel):
    text: str
    entities: List[Entity]


def spans_overlap(a_start, a_end, b_start, b_end):
    return a_start < b_end and b_start < a_end


def reconcile_with_gazetteer(raw_results, text):
    """
    Merges the model's raw entity predictions with the gazetteer's
    independent full-text scan. For each gazetteer match:
      - if it overlaps one or more model-predicted entities, those
        fragments are merged/replaced with the gazetteer's correct,
        full-length span (fixes truncation AND fragmentation)
      - if it overlaps no model entity at all, it's injected as a new
        entity (recovers full recall misses, e.g. "National Assembly"
        the model didn't detect at all)
    Model entities that don't overlap any gazetteer match pass through
    unchanged (still get the exact-match classify() fallback).
    """
    gaz_spans = gazetteer.find_spans_in_text(text)
    used_model_indices = set()
    final_entities = []

    for gspan in gaz_spans:
        overlapping_scores = []
        for i, r in enumerate(raw_results):
            if spans_overlap(gspan["start"], gspan["end"], int(r["start"]), int(r["end"])):
                overlapping_scores.append(float(r["score"]))
                used_model_indices.add(i)

        # Use the highest confidence among any overlapping fragments, or a
        # fixed moderate score if the model missed this span entirely (since
        # there's no model confidence to report for a pure gazetteer injection).
        score = max(overlapping_scores) if overlapping_scores else 0.5

        final_entities.append(Entity(
            entity_group=gspan["entity_group"],
            word=gspan["text"],
            score=score,
            start=gspan["start"],
            end=gspan["end"],
            subcategory=gspan["category"],
            gazetteer_corrected=True,
        ))

    # Carry over any model entities NOT involved in a gazetteer match, unchanged.
    for i, r in enumerate(raw_results):
        if i in used_model_indices:
            continue
        final_entities.append(Entity(
            entity_group=r["entity_group"],
            word=r["word"],
            score=float(r["score"]),
            start=int(r["start"]),
            end=int(r["end"]),
            subcategory=gazetteer.classify(r["word"]),
            gazetteer_corrected=False,
        ))

    final_entities.sort(key=lambda e: e.start)
    return final_entities


@app.get("/")
def health_check():
    return {"status": "ok", "model_loaded": ner_pipeline is not None}


@app.post("/predict", response_model=PredictResponse)
def predict(request: PredictRequest):
    if not request.text or not request.text.strip():
        raise HTTPException(status_code=400, detail="text field cannot be empty")

    if ner_pipeline is None:
        raise HTTPException(status_code=503, detail="Model is still loading, try again shortly")

    processed_text = normalize_elisions(request.text)
    raw_results = ner_pipeline(processed_text)
    entities = reconcile_with_gazetteer(raw_results, processed_text)

    return PredictResponse(text=processed_text, entities=entities)
